### H1N1 and Seasonal Flu Vaccine Uptake
#### Exploratory Data Analysis

In [1]:
# Import packages and custom functions
import sys; sys.path.append("../"); from initialise import *

In [2]:
eda_output = {}

In [3]:
data_types = {
    "respondent_id": "Int64"
    , "h1n1_concern": "Int64"
    , "h1n1_knowledge": "Int64"
    , "behavioral_antiviral_meds": "Int64"
    , "behavioral_avoidance": "Int64"
    , "behavioral_face_mask": "Int64"
    , "behavioral_wash_hands": "Int64"
    , "behavioral_large_gatherings": "Int64"
    , "behavioral_outside_home": "Int64"
    , "behavioral_touch_face": "Int64"
    , "doctor_recc_h1n1": "Int64"
    , "doctor_recc_seasonal": "Int64"
    , "chronic_med_condition": "Int64"
    , "child_under_6_months": "Int64"
    , "health_worker": "Int64"
    , "health_insurance": "Int64"
    , "opinion_h1n1_vacc_effective": "Int64"
    , "opinion_h1n1_risk": "Int64"
    , "opinion_h1n1_sick_from_vacc": "Int64"
    , "opinion_seas_vacc_effective": "Int64"
    , "opinion_seas_risk": "Int64"
    , "opinion_seas_sick_from_vacc": "Int64"
    , "age_group": "category"
    , "education": "category"
    , "race": "category"
    , "sex": "category"
    , "income_poverty": "category"
    , "marital_status": "category"
    , "rent_or_own": "category"
    , "employment_status": "category"
    , "hhs_geo_region": "category"
    , "census_msa": "category"
    , "household_adults": "Int64"
    , "household_children": "Int64"
    , "employment_industry": "category"
    , "employment_occupation": "category"
    , "h1n1_vaccine": "Int64"
    , "seasonal_vaccine": "Int64"
    }

data_dictionary = {
    "h1n1_vaccine": {
        "description": "Whether respondent received H1N1 flu vaccine.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "seasonal_vaccine": {
        "description": "Whether respondent received seasonal flu vaccine.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "respondent_id": {
        "description": "Unique and random identifier.",
        "mappings": {
            None
        }
    },
    "h1n1_concern": {
        "description": "Level of concern about the H1N1 flu.",
        "mappings": {
            0: "Not at all concerned",
            1: "Not very concerned",
            2: "Somewhat concerned",
            3: "Very concerned",
        }
    },
    "h1n1_knowledge": {
        "description": "Level of knowledge about H1N1 flu.",
        "mappings": {
            0: "No knowledge",
            1: "A little knowledge",
            2: "A lot of knowledge",
        }
    },
    "behavioral_antiviral_meds": {
        "description": "Has taken antiviral medications.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_avoidance": {
        "description": "Has avoided close contact with others with flu-like symptoms.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_face_mask": {
        "description": "Has bought a face mask.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_wash_hands": {
        "description": "Has frequently washed hands or used hand sanitizer.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_large_gatherings": {
        "description": "Has reduced time at large gatherings.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_outside_home": {
        "description": "Has reduced contact with people outside of own household.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "behavioral_touch_face": {
        "description": "Has avoided touching eyes, nose, or mouth.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "doctor_recc_h1n1": {
        "description": "H1N1 flu vaccine was recommended by doctor.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "doctor_recc_seasonal": {
        "description": "Seasonal flu vaccine was recommended by doctor.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "chronic_med_condition": {
        "description": "Has any of the listed chronic medical conditions.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "child_under_6_months": {
        "description": "Has regular close contact with a child under the age of six months.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "health_worker": {
        "description": "Is a healthcare worker.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "health_insurance": {
        "description": "Has health insurance.",
        "mappings": {
            0: "No",
            1: "Yes",
        }
    },
    "opinion_h1n1_vacc_effective": {
        "description": "Respondent's opinion about H1N1 vaccine effectiveness.",
        "mappings": {
            1: "Not at all effective",
            2: "Not very effective",
            3: "Don't know",
            4: "Somewhat effective",
            5: "Very effective",
        }
    },
    "opinion_h1n1_risk": {
        "description": "Respondent's opinion about risk of getting sick with H1N1 flu without vaccine.",
        "mappings": {
            1: "Very Low",
            2: "Somewhat low",
            3: "Don't know",
            4: "Somewhat high",
            5: "Very high",
        }
    },
    "opinion_h1n1_sick_from_vacc": {
        "description": "Respondent's worry of getting sick from taking H1N1 vaccine.",
        "mappings": {
            1: "Not at all worried",
            2: "Not very worried",
            3: "Don't know",
            4: "Somewhat worried",
            5: "Very worried",
        }
    },
    "opinion_seas_vacc_effective": {
        "description": "Respondent's opinion about seasonal flu vaccine effectiveness.",
        "mappings": {
            1: "Not at all effective",
            2: "Not very effective",
            3: "Don't know",
            4: "Somewhat effective",
            5: "Very effective",
        }
    },
    "opinion_seas_risk": {
        "description": "Respondent's opinion about risk of getting sick with seasonal flu without vaccine.",
        "mappings": {
            1: "Very Low",
            2: "Somewhat low",
            3: "Don't know",
            4: "Somewhat high",
            5: "Very high",
        }
    },
    "opinion_seas_sick_from_vacc": {
        "description": "Respondent's worry of getting sick from taking seasonal flu vaccine.",
        "mappings": {
            1: "Not at all worried",
            2: "Not very worried",
            3: "Don't know",
            4: "Somewhat worried",
            5: "Very worried",
        }
    },
    "age_group": {
        "description": "Age group of respondent.",
        "mappings": {
            None
        }
    },
    "education": {
        "description": "Self-reported education level.",
        "mappings": {
            None
        }
    },
    "race": {
        "description": "Ethnicity of respondent.",
        "mappings": {
            None
        }
    },
    "sex": {
        "description": "Sex of respondent.",
        "mappings": {
            None
        }
    },
    "income_poverty": {
        "description": "Household annual income of respondent with respect to 2008 Census poverty thresholds.",
        "mappings": {
            None
        }
    },
    "marital_status": {
        "description": "Marital status of respondent.",
        "mappings": {
            None
        }
    },
    "rent_or_own": {
        "description": "Housing situation of respondent.",
        "mappings": {
            None
        }
    },
    "employment_status": {
        "description": "Employment status of respondent.",
        "mappings": {
            None
        }
    },
    "hhs_geo_region": {
        "description": "Respondent's residence using a 10-region geographic classification defined by the U.S. Dept. of Health and Human Services.",
        "mappings": {
            None
        }
    },
    "census_msa": {
        "description": "Respondent's residence within metropolitan statistical areas (MSA) as defined by the U.S. Census.",
        "mappings": {
            None
        }
    },
    "household_adults": {
        "description": "Number of other adults in household, top-coded to 3.",
        "mappings": {
            None
        }
    },
    "household_children": {
        "description": "Number of children in household, top-coded to 3.",
        "mappings": {
            None
        }
    },
    "employment_industry": {
        "description": "Type of industry respondent is employed in.",
        "mappings": {
            None
        }
    },
    "employment_occupation": {
        "description": "Type of occupation of respondent.",
        "mappings": {
            None
        }
    }
}

In [4]:
eda_output.update({"data_types": data_types, "data_dictionary": data_dictionary})

In [5]:
# Read in data
df = pd.read_csv("data/training_set_features.csv", dtype = data_types).merge(pd.read_csv("data/training_set_labels.csv", dtype = data_types))
df.drop("respondent_id", axis = 1, inplace = True)

In [6]:
# Initial inspection of data
df.head()

,h1n1_concern,h1n1_knowledge,behavioral_antiviral_meds,behavioral_avoidance,behavioral_face_mask,behavioral_wash_hands,behavioral_large_gatherings,behavioral_outside_home,behavioral_touch_face,doctor_recc_h1n1,...,rent_or_own,employment_status,hhs_geo_region,census_msa,household_adults,household_children,employment_industry,employment_occupation,h1n1_vaccine,seasonal_vaccine
0,1,0,0,0,0,0,0,1,1,0,...,Own,Not in Labor Force,oxchjgsf,Non-MSA,0,0,NaN,NaN,0,0
1,3,2,0,1,0,1,0,1,1,0,...,Rent,Employed,bhuqouqj,"MSA, Not Principle City",0,0,pxcmvdjn,xgwztkwe,0,1
2,1,1,0,1,0,0,0,0,0,<NA>,...,Own,Employed,qufhixun,"MSA, Not Principle City",2,0,rucpziij,xtkaffoo,0,0
3,1,1,0,1,0,1,1,0,0,0,...,Rent,Not in Labor Force,lrircsnp,"MSA, Principle City",0,0,NaN,NaN,0,1
4,2,1,0,1,0,1,1,0,1,0,...,Own,Employed,qufhixun,"MSA, Not Principle City",1,0,wxleyezf,emcorrxb,0,0

In [7]:
eda_output.update({"data_preview": df})

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26707 entries, 0 to 26706
Data columns (total 37 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   h1n1_concern                 26615 non-null  Int64
 1   h1n1_knowledge               26591 non-null  Int64
 2   behavioral_antiviral_meds    26636 non-null  Int64
 3   behavioral_avoidance         26499 non-null  Int64
 4   behavioral_face_mask         26688 non-null  Int64
 5   behavioral_wash_hands        26665 non-null  Int64
 6   behavioral_large_gatherings  26620 non-null  Int64
 7   behavioral_outside_home      26625 non-null  Int64
 8   behavioral_touch_face        26579 non-null  Int64
 9   doctor_recc_h1n1             24547 non-null  Int64
 10  doctor_recc_seasonal         24547 non-null  Int64
 11  chronic_med_condition        25736 non-null  Int64
 12  child_under_6_months         25887 non-null  Int64
 13  health_worker                25903 non-null  Int64
 14  health_insurance             14433 non-null  Int64
 15  opinion_h1n1_vacc_effective  26316 non-null  Int64
 16  opinion_h1n1_risk            26319 non-null  Int64
 17  opinion_h1n1_sick_from_vacc  26312 non-null  Int64
 18  opinion_seas_vacc_effective  26245 non-null  Int64
 19  opinion_seas_risk            26193 non-null  Int64
 20  opinion_seas_sick_from_vacc  26170 non-null  Int64
 21  age_group                    26707 non-null  category
 22  education                    25300 non-null  category
 23  race                         26707 non-null  category
 24  sex                          26707 non-null  category
 25  income_poverty               22284 non-null  category
 26  marital_status               25299 non-null  category
 27  rent_or_own                  24665 non-null  category
 28  employment_status            25244 non-null  category
 29  hhs_geo_region               26707 non-null  category
 30  census_msa                   26707 non-null  category
 31  household_adults             26458 non-null  Int64
 32  household_children           26458 non-null  Int64
 33  employment_industry          13377 non-null  category
 34  employment_occupation        13237 non-null  category
 35  h1n1_vaccine                 26707 non-null  Int64
 36  seasonal_vaccine             26707 non-null  Int64
dtypes: Int64(25), category(12)
memory usage: 6.2 MB

In [9]:
# For the purpose of eda we can drop `Response ID`
# df.drop("respondent_id", axis = 1, inplace = True)
eda_output.update({"describe_numeric": prettyDescribe(df, shape = False)})
prettyDescribe(df, shape = False)

,min,mean,max,std,25%,50%,75%,na_values
h1n1_concern,0.0,1.62,3.0,0.91,1.0,2.0,2.0,92 (0.34%)
h1n1_knowledge,0.0,1.26,2.0,0.62,1.0,1.0,2.0,116 (0.43%)
behavioral_antiviral_meds,0.0,0.05,1.0,0.22,0.0,0.0,0.0,71 (0.27%)
behavioral_avoidance,0.0,0.73,1.0,0.45,0.0,1.0,1.0,208 (0.78%)
behavioral_face_mask,0.0,0.07,1.0,0.25,0.0,0.0,0.0,19 (0.07%)
behavioral_wash_hands,0.0,0.83,1.0,0.38,1.0,1.0,1.0,42 (0.16%)
behavioral_large_gatherings,0.0,0.36,1.0,0.48,0.0,0.0,1.0,87 (0.33%)
behavioral_outside_home,0.0,0.34,1.0,0.47,0.0,0.0,1.0,82 (0.31%)
behavioral_touch_face,0.0,0.68,1.0,0.47,0.0,1.0,1.0,128 (0.48%)
doctor_recc_h1n1,0.0,0.22,1.0,0.41,0.0,0.0,0.0,"2,160 (8.09%)"
doctor_recc_seasonal,0.0,0.33,1.0,0.47,0.0,0.0,1.0,"2,160 (8.09%)"
chronic_med_condition,0.0,0.28,1.0,0.45,0.0,0.0,1.0,971 (3.64%)
child_under_6_months,0.0,0.08,1.0,0.28,0.0,0.0,0.0,820 (3.07%)
health_worker,0.0,0.11,1.0,0.32,0.0,0.0,0.0,804 (3.01%)
health_insurance,0.0,0.88,1.0,0.33,1.0,1.0,1.0,"12,274 (45.96%)"
opinion_h1n1_vacc_effective,1.0,3.85,5.0,1.01,3.0,4.0,5.0,391 (1.46%)
opinion_h1n1_risk,1.0,2.34,5.0,1.29,1.0,2.0,4.0,388 (1.45%)
opinion_h1n1_sick_from_vacc,1.0,2.36,5.0,1.36,1.0,2.0,4.0,395 (1.48%)
opinion_seas_vacc_effective,1.0,4.03,5.0,1.09,4.0,4.0,5.0,462 (1.73%)
opinion_seas_risk,1.0,2.72,5.0,1.39,2.0,2.0,4.0,514 (1.92%)
opinion_seas_sick_from_vacc,1.0,2.12,5.0,1.33,1.0,2.0,4.0,537 (2.01%)
household_adults,0.0,0.89,3.0,0.75,0.0,1.0,1.0,249 (0.93%)
household_children,0.0,0.53,3.0,0.93,0.0,0.0,1.0,249 (0.93%)
h1n1_vaccine,0.0,0.21,1.0,0.41,0.0,0.0,0.0,0 (0.00%)
seasonal_vaccine,0.0,0.47,1.0,0.5,0.0,0.0,1.0,0 (0.00%)

In [10]:
eda_output.update({"describe_category": prettyDescribe(df, data_type = "category", shape = False)})
prettyDescribe(df, data_type = "category", shape = False)

,unique,top,top_freq,na_values
age_group,5,65+ Years,"19,864 (74.38%)",0 (0.00%)
education,4,College Graduate,"16,610 (62.19%)","1,407 (5.27%)"
race,4,White,"5,485 (20.54%)",0 (0.00%)
sex,2,Female,"10,849 (40.62%)",0 (0.00%)
income_poverty,3,"<= $75,000, Above Poverty","13,930 (52.16%)","4,423 (16.56%)"
marital_status,2,Married,"13,152 (49.25%)","1,408 (5.27%)"
rent_or_own,2,Own,"7,971 (29.85%)","2,042 (7.65%)"
employment_status,3,Employed,"13,147 (49.23%)","1,463 (5.48%)"
hhs_geo_region,10,lzgpxyit,"22,410 (83.91%)",0 (0.00%)
census_msa,3,"MSA, Not Principle City","15,062 (56.40%)",0 (0.00%)
employment_industry,21,fcxhlnwr,"24,239 (90.76%)","13,330 (49.91%)"
employment_occupation,23,xtkaffoo,"24,929 (93.34%)","13,470 (50.44%)"

In [11]:
# Inspect our target variable `full vaccine`
fig = (px
 .pie(df.assign(h1n1_vaccine = lambda x: x["h1n1_vaccine"].apply(lambda x: f'{x}: {data_dictionary["h1n1_vaccine"]["mappings"][x]}')),
      names = "h1n1_vaccine", color = "h1n1_vaccine", color_discrete_map = {"0: No": px.colors.qualitative.Set1[0], "1: Yes": px.colors.qualitative.Set1[1]})
 .update_traces(marker_line_width = 1, marker_line_color = "white")
 .update_layout(title = dict(text = "H1N1 Vaccine", x = 0.5))
)

# config = {"staticPlot": True}
fig.show()
eda_output.update({"h1n1_vaccine": fig})

In [12]:
features = [x for x in df.columns if x not in ["h1n1_vaccine", "respondent_id"]]

In [ ]:
# Inspect the 3 highest and lowest correlated features with `h1n1_vaccine`
for var in features:
    
    fig = make_subplots(rows = 1, cols = 2, subplot_titles = ["Histogram", "100% Stacked Bar Chart"])
    
    mappings = " | ".join([f"{x}:  {y}" for x, y in data_dictionary[var]["mappings"].items()]) if data_dictionary[var]["mappings"] != {None} else ""
    tickvals, nbins = (df[var].dropna().unique(), None) if (df[var].dtype == "Int64") & (len(df[var].dropna().unique()) < 10) else (None, 10)
    df_temp = df.value_counts(["h1n1_vaccine", var]).reset_index(name = "freq").sort_values(["h1n1_vaccine", var]).reset_index(drop = True)
    
    for col in [1, 2]:
        
        text_auto = "," if col == 1 else ".1f"
        df_temp["freq"] = df_temp["freq"] / df_temp.groupby([var])["freq"].transform("sum") if col == 2 else df_temp["freq"]

        trace = px.bar(df_temp.assign(h1n1_vaccine = lambda x: x["h1n1_vaccine"].apply(lambda x: f'{x}: {data_dictionary["h1n1_vaccine"]["mappings"][int(x)]}')), 
                       x = var, y = "freq", color = "h1n1_vaccine", text_auto = text_auto,
                       category_orders = {"h1n1_vaccine": ["0: No", "1: Yes"]},
                       color_discrete_map = {"0: No": px.colors.qualitative.Set1[0], "1: Yes": px.colors.qualitative.Set1[1]})

        for data in trace.data:
            fig.add_trace(data, row = 1, col = col)
    
    (fig
     .update_layout(barmode = "stack", template = "plotly",
                    title = dict(text = f"{var.replace('_', ' ').title()}<br><br><sup>{data_dictionary[var]['description']}</sup>", x = 0.5, y = 0.9),
                    margin = dict(t = 150),
                    xaxis = dict(title = None, tickvals = tickvals),
                    xaxis2 = dict(title = None, tickvals = tickvals),
                    yaxis = dict(title = "Count", tickformat = ","),
                    yaxis2 = dict(title = "Percent"),
                    legend = dict(title = "H1N1 Vaccine"),
                    height = 600, width = 1000
                    )

     .add_annotation(text = mappings, showarrow = False, xref = "paper", x = 0.5, yref = "paper", y = -0.15)
    )
    
    names = set()
    fig.for_each_trace(lambda x: x.update(showlegend = False) if (x.name in names) else names.add(x.name))
    
    eda_output.update({f"{var}_distribution": fig})

In [ ]:

for var in features:

    fig = (px.bar(pd.DataFrame({
        "class": ["Populated", "Missing"],
        "percent": [1 - sum(df[var].isna()) / len(df), sum(df[var].isna()) / len(df)]
        }).round(3), y = [0, 0], x = "percent", color = "class", barmode = "stack", height = 100, width = 1000,
        category_orders = {"class": ["Populated", "Missing"]},
        color_discrete_map = {"Populated": px.colors.qualitative.Set1[1], "Missing": px.colors.qualitative.Set1[0]},
        pattern_shape = "class", pattern_shape_sequence = ["", "/"])
    .update_traces(opacity = 1, orientation = "h", showlegend = False)
    .update_layout(margin = dict(t = 0, b = 0, l = 0, r = 0), 
                    xaxis = dict(title = f"{var.replace('_', ' ').title()}: Missing observations (%)", tickvals = [0, 0.25, 0.5, 0.75, 1], range = [0, 1]), 
                    yaxis = dict(title = None, showticklabels = False, showgrid = False))
    )

    eda_output.update({f"{var}_missing": fig})

In [ ]:
for var in features:

    if (df[var].dtype == "O") | (df[var].dtype == "category"): continue

    corr = df[["h1n1_vaccine", var]].corr(method = "pearson").loc["h1n1_vaccine", var].round(3)
    fig = (px.scatter(pd.DataFrame({"x": corr, "y": [0]}), x = "x", y = "y", height = 100, width = 1000
                # color = "x", range_color = [-1, 1], color_continuous_scale = [(0, px.colors.qualitative.Set1[1]), (1, px.colors.qualitative.Set1[0])]
                )
    .update_traces(marker_symbol = "arrow-bar-left" if corr < 0 else "arrow-bar-right",
                   marker_color = px.colors.qualitative.Set1[1] if corr < 0 else px.colors.qualitative.Set1[0],
                   marker_size = 40, showlegend = False)
    .update_xaxes(range = [-1, 1])
    .update_layout(coloraxis_showscale = False, 
                    margin = dict(t = 0, b = 0, l = 0, r = 0), 
                    xaxis = dict(title = f"{var.replace('_', ' ').title()}: Correlation to H1N1 Vaccine", tickvals = [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75, 1]), 
                    yaxis = dict(title = None, showticklabels = False, showgrid = False))
    )

    eda_output.update({f"{var}_corr": fig})

In [16]:
to_pkl(eda_output, "eda_output.pickle")
# eda_output = read_pkl("eda_output.pickle")

In [17]:
eda_output.keys()

dict_keys(['data_types', 'data_dictionary', 'data_preview', 'describe_numeric', 'describe_category', 'h1n1_vaccine', 'h1n1_concern_distribution', 'h1n1_knowledge_distribution', 'behavioral_antiviral_meds_distribution', 'behavioral_avoidance_distribution', 'behavioral_face_mask_distribution', 'behavioral_wash_hands_distribution', 'behavioral_large_gatherings_distribution', 'behavioral_outside_home_distribution', 'behavioral_touch_face_distribution', 'doctor_recc_h1n1_distribution', 'doctor_recc_seasonal_distribution', 'chronic_med_condition_distribution', 'child_under_6_months_distribution', 'health_worker_distribution', 'health_insurance_distribution', 'opinion_h1n1_vacc_effective_distribution', 'opinion_h1n1_risk_distribution', 'opinion_h1n1_sick_from_vacc_distribution', 'opinion_seas_vacc_effective_distribution', 'opinion_seas_risk_distribution', 'opinion_seas_sick_from_vacc_distribution', 'age_group_distribution', 'education_distribution', 'race_distribution', 'sex_distribution', 'income_poverty_distribution', 'marital_status_distribution', 'rent_or_own_distribution', 'employment_status_distribution', 'hhs_geo_region_distribution', 'census_msa_distribution', 'household_adults_distribution', 'household_children_distribution', 'employment_industry_distribution', 'employment_occupation_distribution', 'seasonal_vaccine_distribution', 'h1n1_concern_missing', 'h1n1_knowledge_missing', 'behavioral_antiviral_meds_missing', 'behavioral_avoidance_missing', 'behavioral_face_mask_missing', 'behavioral_wash_hands_missing', 'behavioral_large_gatherings_missing', 'behavioral_outside_home_missing', 'behavioral_touch_face_missing', 'doctor_recc_h1n1_missing', 'doctor_recc_seasonal_missing', 'chronic_med_condition_missing', 'child_under_6_months_missing', 'health_worker_missing', 'health_insurance_missing', 'opinion_h1n1_vacc_effective_missing', 'opinion_h1n1_risk_missing', 'opinion_h1n1_sick_from_vacc_missing', 'opinion_seas_vacc_effective_missing', 'opinion_seas_risk_missing', 'opinion_seas_sick_from_vacc_missing', 'age_group_missing', 'education_missing', 'race_missing', 'sex_missing', 'income_poverty_missing', 'marital_status_missing', 'rent_or_own_missing', 'employment_status_missing', 'hhs_geo_region_missing', 'census_msa_missing', 'household_adults_missing', 'household_children_missing', 'employment_industry_missing', 'employment_occupation_missing', 'seasonal_vaccine_missing', 'h1n1_concern_corr', 'h1n1_knowledge_corr', 'behavioral_antiviral_meds_corr', 'behavioral_avoidance_corr', 'behavioral_face_mask_corr', 'behavioral_wash_hands_corr', 'behavioral_large_gatherings_corr', 'behavioral_outside_home_corr', 'behavioral_touch_face_corr', 'doctor_recc_h1n1_corr', 'doctor_recc_seasonal_corr', 'chronic_med_condition_corr', 'child_under_6_months_corr', 'health_worker_corr', 'health_insurance_corr', 'opinion_h1n1_vacc_effective_corr', 'opinion_h1n1_risk_corr', 'opinion_h1n1_sick_from_vacc_corr', 'opinion_seas_vacc_effective_corr', 'opinion_seas_risk_corr', 'opinion_seas_sick_from_vacc_corr', 'household_adults_corr', 'household_children_corr', 'seasonal_vaccine_corr'])